### ISSUE TITLE
Create Initial Version of Supervisor Agent for Kyma Companion

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#112]
### Description

The goal of this task is to create the initial version of the supervisor agent for Kyma Companion. This includes expanding the chat controller to accept necessary information, setting up a proper technique for the supervisor agent, and creating sample nodes for two agents and one tool for future development.

### Subtasks

**1. Expand Chat Controller:**

- Modify the chat controller to accept session ID and cluster access information from the busload backend.
- Ensure the chat controller can properly handle and store this information for use by the supervisor agent.

**2. Set Up Supervisor Agent Technique:**
Select and set up a suitable technique for the supervisor agent (for example Planning, Routing).

**3. Create Sample Nodes:**

- Develop dummy nodes for two agents that will be used by the supervisor agent. (Kyma agent, Kubernetes agent)
- Develop a dummy node for one tool that will be utilized in future development. (Response conversion tool)

### Acceptance Criteria

- [x] The chat controller is expanded to accept session ID and cluster access information from the busload backend.
- [x] The supervisor agent technique (for example Planning, Routing) is set up.
- [x] Dummy nodes for two agents are created and functional.
- [x]  Planner should consider conversation history. 
   - If possible, supervisor/planner should answer the common questions.

**Comment by Teneroy** [comment]
https://github.com/langchain-ai/langgraph/blob/main/examples/multi_agent/agent_supervisor.ipynb

**Comment by Teneroy** [comment]
Make planner more intelligent by adding information from the state like conversation history and/or messages
Improve Finalizer so it would be able to analyze whether responses from agents make sense, and fail accordingly when they are not
Merge planner and common node for common question. In case there is no need to go with the plan, planner should be able to generate the response to user directly without going to the task executor

**Comment by muralov** [comment]
Improvements in the code:
- [ ] Upgrade generative-ai-hub-sdk package
- [ ] Improve route function according the [discussion](https://sap-btp.slack.com/archives/C07FWF4LFKM/p1724927386684859)
- [ ] Add unit tests for KymaGraph

**Comment by Teneroy** [comment]
Proper streaming format

**Comment by muralov** [comment]
Things that can be improved in the future:
    - sometimes supervisor is failing with output parser error
    - error handling can be improved with retry and fallback logic
    - retry logic is introduced for each node

**Comment by muralov** [comment]
current LangGraph: 
![graph](https://github.com/user-attachments/assets/1053adb1-7141-4ce6-9c86-796e02133d55)
