### ISSUE TITLE
Spike: Draft Initial Architecture of Kyma Companion Agents

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#114]
### Description

This spike aims to draft the initial architecture of Kyma Companion agents, focusing on high-priority capabilities, their communication, interaction with external systems, and ensuring flexibility for future experimentation. The outcome will be a documented and discussed architecture ready for implementation.

### Timebox

5 working days

### Participants

Developer
Product Owner (PO)

### Tasks

**1. Draft Agents and Communication:**

- Identify and draft initial ideas for agents necessary to cover high-priority capabilities.
- Outline the communication flow between these agents.
- Define the data that is being exchanged between those agents(rough concept)

**2. Draft Tools for Agents:**

- Identify and draft the necessary tools for the agents to perform their tasks.

**3. Draft Interaction with External Systems:**

- Define how agents and tools will interact with external systems such as databases and clusters.

**4. Draft Tool Structure:**

- Create an approximate picture of how the tools should be structured and designed.

**5. Address Pre-Deployment Issues:**

- Consider and document strategies for rate limiting, misuse protection, and monitoring.

**6. Ensure Flexibility:**

- Design the architecture to be flexible and allow for future experimentation and changes.

**7. Document Proposed Architecture:**

- Compile all drafts and designs into a comprehensive architecture document.

**8. Team Discussion and Feedback:**

- Present the proposed architecture to the team.
- Gather feedback and make necessary adjustments based on team discussions.

### Acceptance Criteria

- [ ]  Initial ideas for agents and their communication flow are drafted.
- [ ]  Tools necessary for the agents are identified and drafted.
- [ ]  Interaction of agents and tools with external systems is defined.
- [ ]  An approximate picture of the tools' structure is created.
- [ ]  Pre-deployment issues like rate limiting, misuse protection, and monitoring are addressed.
- [ ]  The architecture is designed to be flexible and allow for experimentation.
- [ ]  The proposed architecture is documented comprehensively.
- [ ]  The architecture is discussed with the team, and feedback is incorporated.
- [ ]  The team agrees on the proposed architecture, with adjustments made as necessary.

**Comment by grischperl** [comment]
**Agents Architecture**
- [ ] Initial Rough Draft
   - [ ] What agents should exist?
   - [ ] What is each agents responsibility?
   - [ ] What tool does each agent have?
   - [ ] What is the rough ability of each tool?
- [ ] Overall information flow is documented with a graph 

**Supervisor Agent**
- [ ] Draft an initial process flow for the Supervisor.
- [ ] What information does the Supervisor pass?
- [ ] Does only the Supervisor have access to conversation history from RedisDB?
- [ ] How does the Supervisor come up with a plan? Up front or flexible?

**Kyma Agent**
- [ ] Detailed process flow
- [ ] Agents communication flow: 
   - [ ] What information is passed?
   - [ ] What resource context is needed?
   - [ ] Do Agents use ReAct vs Reflection?
   - [ ] Bigger picture of nodes and conditional edges in the communication flow
   - [ ] How can this be achieved in the future when multi-tab, switching between resource context, will be introduced?
  
**Kubernetes Agent**
- [ ] Detailed process flow
- [ ] Agents communication flow: 
   - [ ] What information is passed?
   - [ ] What resource context is needed?
   - [ ] Do Agents use ReAct vs Reflection?
   - [ ] Bigger picture of nodes and conditional edges in the communication flow
   - [ ] How can this be achieved in the future when multi-tab, switching between resource context, will be introduced?
 
**RAG**
- [ ] What is the process flow?
- [ ] What is the information flow?
- [ ] Where do you need to pay attention on prompting when implementing?
- [ ] Graph to show the process flow

**Resource Retrieval Tool**
- [ ] What is the process flow?
- [ ] What is the information flow?
- [ ] Where do you need to pay attention on prompting when implementing?
- [ ] Graph to show the process flow
- [ ] How are duplicates removed?

**Response Conversion Tool**
- [ ] What is the process flow?
- [ ] What is the information flow?
- [ ] Where do you need to pay attention on prompting when implementing?
- [ ] Graph to show the process flow
- [ ] How are duplicates removed?

**Pre-Deployment Issues**
- [ ]  Pre-deployment issues like rate limiting, misuse protection, and monitoring are addressed.

**Team Agreement**
- [ ]  The architecture is discussed with the team, and feedback is incorporated.
- [ ]  The team agrees on the proposed architecture, with adjustments made as necessary.
