### ISSUE TITLE
Rework Trigger of Pull Build Image GitHub Action

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#136]
### Description:
The [Pull Build Image](https://github.com/kyma-project/kyma-companion/actions/workflows/pull-build-image.yaml) job is currently triggered unnecessarily, including for changes in the test folder, PR title updates, and .md file modifications. Optimize the job to execute only when relevant changes are made, improving CI efficiency.
This should concern also other jobs which are dependent on pull-build-image job like, for example, evaluation test. If there are no changes in the source code, there is no need to trigger evaluation test

### Tasks:

- Analyze the current job configuration to identify unnecessary triggers
- Modify the workflow file to exclude triggers for test folder updates, PR title changes, and .md file modifications
- Implement conditional job execution based on relevant file changes, and execution of jobs dependent on the build job
- Update documentation to reflect the new job trigger conditions

### Acceptance Criteria:

- [x] The Pull Build Image job only triggers when changes are made to relevant files
- [x] Jobs which are dependent on the build-pull-image job are triggered only when build-pull-image is triggered
- [x] Project documentation is updated to explain when the job will and will not run

**Comment by the1bit** [comment]
PR: https://github.com/kyma-project/kyma-companion/pull/207
