### ISSUE TITLE
Setup the Development Cluster

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#25]
**Description:**
Set up the necessary infrastructure for the development cluster, including HANA DB, Redis, and AI Core with increased rate limits. Additionally, configure the cluster for testing pull requests (PRs) and document the entire setup process. We should use BTP operator to use services.

**Subtasks:**
1. **Setup HANA DB:** Install and configure HANA DB for the development cluster.
2. **Setup Redis:** Install and configure Redis for the development cluster.
3. **Setup AI Core:** Install and configure AI Core for the development cluster, ensuring the rate limits are increased.
4. **Configure Cluster for PR Testing:** Setup the development cluster to be used for testing PRs.
5. **Documentation:** Document the entire setup process for HANA DB, Redis, AI Core, and the development cluster configuration.**Acceptance Criteria:**

- [x] HANA DB is set up and configured in the development cluster.
- [x] Redis is set up and configured in the development cluster.
- [x] AI Core is set up ~with increased rate limits~ and configured in the development cluster.
- [x] Development cluster is configured and ready for testing PRs.
- [x] Comprehensive documentation is provided for the entire setup process.

> Note: Currently, rate limits need to be increased by model by opening a ticket [(ref)](https://sap-ml.slack.com/archives/C01DZC6EGB0/p1719903321867399?thread_ts=1719889088.225079&cid=C01DZC6EGB0). As we have no data on this now, this will be tackled during the development stage.

**Comment by Teneroy** [comment]
split into the new task Automation: Provide scripts for automatic configuration of the cluster

**Comment by the1bit** [comment]
Hana DB related code modifications: https://github.tools.sap/kyma/ai-force/pull/172

**Comment by the1bit** [comment]
Documentation by Tibi: https://github.tools.sap/I505083/ai-force/tree/setup-development-cluster

**Comment by grischperl** [comment]
- beginning setup of Kyma cluster
- sync again with Tibi about how to perform the next steps, which to skip, what to look out for etc.
- begin documentation of each step

**Comment by grischperl** [comment]
- apply service account, rbac and configmap
- configure SAP Launchpad
- figure out which roles are required
- start with setting up the needed models

continue with the needed models, add everything to the configmap and continue with backend deployment

**Comment by grischperl** [comment]
- finish configuring AI Core and Launchpad
- document all the steps and the pieces of official documentation about it
- SAP Launchpad stopped working in the evening without any reason I could find out

continue with setting up the needed models, inquiring in the official support about the Launchpad troubles and test the deployed backend

**Comment by grischperl** [comment]
- create all the needed models
- create the config map and apply to the cluster
- deploy ai-backend but: Error/CrashLoopBackOff

```
reason: ContainersNotReady
lastState:
      terminated:
        containerID: containerd://190325b31421a274cb8251d7acdeb62b1f471d763864c944bd66390647b3df7f
        exitCode: 3
        reason: Error
```

**Comment by grischperl** [comment]
PR: https://github.tools.sap/kyma/ai-force/pull/186

**Comment by grischperl** [comment]
- pair with Tibor to create Hana DB instance
- split task of documenting the steps
- add configuration to docu and to cluster
- debug: make sure to `Allow all IP addresses` in Hana DB configuration

**Comment by the1bit** [comment]
**Hana DB:**
- Prerequisites
- Entitlements in the Subaccount
- Create a new instance of the SAP Hana Cloud Database
- Add permissions on SAP Hana Cloud services
- Create Hana service instance in Kyma runtime
- Reset DBADMIN password on SAP Hana Cloud Central
- Login to the SAP Hana Cloud Instance with DBADMIN user
- Create new instance user (optional)
- Get connection details for Kyma Companion

**Redis:**
- Bitnami redis installation

**Comment by grischperl** [comment]
- finish the documentation
- add access rights to the whole team to the cluster
- test an API endpoint: receiving error 500

documentation needs two small follow-up q's answered
error 500 needs to be investigated so that PRs are ready to be tested on the cluster

@Teneroy RBAC permissions are currently very permissive, there probably needs to be a follow up issue to figure out the minimum required permissions
