### ISSUE TITLE
Prepare Basic Tests

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#26]
**Description:**
Prepare and introduce basic tests such as build tests, health check tests, and unit tests. These tests should run against pull requests (PRs) and prevent merging if any tests fail. Integrate these tests into the existing testing pipeline.

**Tasks:**
1. **Prepare Basic Tests:**
   - Develop build tests to ensure the application builds successfully.
   - Create health check tests to verify the application's basic functionality and endpoints.  (docker run)
   - Implement an action to ensure we can't merge the PR until tests are passed.
   - Implement linting checks
2. **Integrate Tests into Pipeline:**
   - Add the prepared tests to the testing pipeline.
   - Ensure tests run automatically against all PRs.
   - Configure the pipeline to block merging of PRs with failing tests.
 
**Acceptance Criteria:**

- [x] Build tests are developed and verify successful application builds. [(action)](https://github.com/kyma-project/kyma-companion/blob/main/.github/workflows/pull-build-image.yaml)
- [x] Health check tests are created and validate the basic functionality and endpoints. (docker run)
- [x] All tests are integrated into the testing pipeline.
- [x] Tests run automatically against PRs, and merging is blocked if tests fail.
- [x] Linting checks are implemented [(action)](https://github.com/kyma-project/kyma-companion/blob/main/.github/workflows/lint-code.yml)
- [x] Unit tests are implemented [(action)](https://github.com/kyma-project/kyma-companion/blob/main/.github/workflows/unit-test.yaml)

**Comment by grischperl** [comment]
Create GitHub Action for:
 - linting using [ruff](https://github.com/astral-sh/ruff)
 - type checking using [mypy](https://github.com/python/mypy)
 - formatting using [black](https://github.com/psf/black)

Execute these using [poethepoet](https://github.com/nat-n/poethepoet)

Fix all found linting, type checking and formatting errors

PR: [kyma-companion/#66](https://github.com/kyma-project/kyma-companion/pull/66)

**Comment by the1bit** [comment]
`ERRO[0000] Error while retrieving image from cache: python:3.12.4-slim-bullseye image not found on any configured mapped registries for python:3.12.4-slim-bullseye`

We need to add the python:3.12.4-slim-bullseye to the image-syncer as @grischperl suggested
