### ISSUE TITLE
Epic: Develop Beta of Kyma Companion

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#275]
[Moved to](https://github.tools.sap/kyma/ai-force/issues/272)

**Comment by mfaizanse** [comment]
**Main topics:**
- [ ] Correctness of answers
  - [ ] Kyma contextual knowledge
  - [ ] Internal flow of graph
- [ ] Testing

**Comment by mfaizanse** [comment]
- fix bugs 
- token limit for rate limiting
- k8s api tool calls / invalid tool calls / wrong k8s kinds
- busola docs / Kyma docs
- Plutono dashboard
- Gatekeeper
- Cluster scoped questions
- Testing improvement
- Agent prompt improvements
