### ISSUE TITLE
Initial questions at the beginning of the conversation

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#29]
### Description

The goal of this task is to update the initialization controller for the Kyma Companion to streamline the setup process when a request is received. The steps involve initializing conversation history, retrieving information from the Kubernetes cluster, and generating initial questions based on the retrieved context. The function to retrieve information from the Kubernetes cluster must be reusable and manage access control effectively. Context is gotten from the resources we look at in busola-ui

### Subtasks

**1. Update Initialization Controller:**

- Modify the initialization controller to handle incoming requests for initializing the Kyma Companion interaction.

 **2. Initialize Conversation History:**

- Develop functionality to initialize the conversation history by inserting context related to the resource being discussed.

**3. Develop Information Retrieval Function:**

- Create a function to retrieve information from the Kubernetes and Kyma cluster based on access information provided by the busload backend.
- Ensure this function is reusable and manages access control properly, preventing unauthorized access.
- Use these resources to form a context for the next steps.

**4. Generate Initial Questions:**

- Develop functionality to generate up to 5 initial questions based on the retrieved context.
- Ensure a balance between speed and functionality when selecting the appropriate model for question generation.

**5. Return Initial Questions:**

- Ensure the generated questions are returned as the response to the initialization request.

**6. Testing and Performance Metrics:**

- Write down a test in pytest to asses whether question generation exceeds on average 2.5 seconds or not.

### Acceptance Criteria

- [x]  The initialization controller handles incoming requests and initializes the conversation history with relevant context.
- [x]  The function to retrieve information from the Kubernetes cluster is reusable and includes effective access control.
- [x]  The necessary Kubernetes or Kyma resources are retrieved and used to form context for question generation.
- [x]  Up to 5 initial questions are generated based on the retrieved context.
- [x]  The generated questions are returned as part of the initialization response.
- [x]  The question generation process is tested, test is written, and the average time taken for generating questions does not exceed 2.5 seconds.

**Comment by Teneroy** [comment]
Before the planning have discussion on how api should look like

**Comment by Teneroy** [comment]
Create a spike or an issue straight away to choose the necessary tool for prompt testing and integrate it into the companion

**Comment by mfaizanse** [comment]
<img width="1121" alt="image" src="https://github.com/user-attachments/assets/577f21a5-9e5c-4601-8acb-d3c1e05e7b18">

**Comment by mfaizanse** [comment]
**Phase 1:**

1. Introduce a new API `/conversations`.
2. Inside the API, extract the response body and headers for the k8s cluster. Follow the API structure described in the doc: `ai-force/docs/Readme.md`
3. Query the Kubernetes cluster using k8s python client to get the relevant data.
4. Create the promptTemplate for initial questions.
5. Inject the kubernetes information as context in the prompt.
6. Query the LLM using LangChain or naked Gemini for initial questions.
7. Return the response as described in doc: `ai-force/docs/Readme.md`

**Phase 2:**
1. Add tests for correctness and performance.

**Phase 3:**
1. Check if Mansur has initialized the LangGraph.
2. Integrate the LangGraph instead of directly using LangChain or naked Gemini for initial questions

**Phase 4:**
1. Use LangGraph Checkpointing to save the conversation history.

**Comment by mfaizanse** [comment]
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/5a6d5db1-ff69-46d3-8a43-427fd0fa3d6f">

**Comment by mfaizanse** [comment]
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/749635b1-2275-4b3a-84ea-2a051d0b3c31">

**Comment by mfaizanse** [comment]
## Sample Request:

- URI: `POST /api/conversations`
- Body:
  ```
  {
    "resource_kind": "Deployment",
	  "resource_api_version": "apps/v1",
	  "resource_name": "nginx",
    "namespace": "nginx-wrong-image"
  }
  ```
- Headers:
  ```
  x-k8s-authorization: abc
  x-cluster-url: https://api.xyz.shoot.canary.k8s-hana.ondemand.com
  x-cluster-certificate-authority-data: abc
  ```

## Sample Response:

**Body:**
<img width="681" alt="image" src="https://github.com/user-attachments/assets/990ec321-4a36-484c-82c6-a5d3c0cbd563">

**Headers:**
<img width="806" alt="image" src="https://github.com/user-attachments/assets/5b9f79e3-4657-4af9-879b-23c0509302f7">

**Comment by mfaizanse** [comment]
## Response time summary output in Blackbox tests:

![image](https://github.com/user-attachments/assets/8050774d-c2a3-41a1-a4b8-555bbb9c792f)

**Comment by mfaizanse** [comment]
- [ ] Save the context as well
