### ISSUE TITLE
Develop Kyma Companion Manager Operator (MVP)

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#58]
**Description:**
Develop the MVP (Minimum Viable Product) of the Kyma Companion Manager operator, which will manage the deployments of the Kyma Companion components. The manager should facilitate the Companion Custom Resource (CR) to handle HANA Vector DB, Redis, and AI-Core secrets. Documentation should be provided on how to deploy the manager both locally and to the development cluster. For this task it is OK to use a dummy PR

**Tasks:**

1. **Develop Kyma Companion Manager Operator:** Create the Kyma Companion Manager operator to manage the deployments of various Kyma Companion components.
- provide provisioning functionality
- provide updating functionality
- provide deprovisioning functionality
2. **Documentation:** Document the steps to deploy the Kyma Companion Manager operator both locally and to the development cluster.

**Acceptance Criteria:**

- [x] Kyma Companion Manager operator is developed and capable of managing component deployments.
- [x] Dummy secrets are introduced for managing HANA Vector DB, Redis, and AI-Core configurations effectively.
- [x] Comprehensive documentation is provided for deploying the manager locally and to the development cluster.
- [x] Necessary tests are implemented

**Comment by mfaizanse** [comment]
**Checklist:**
- [ ] scaffold out a new project
- [ ] Create a companion CRD with empty spec.
- [ ] Add finalizers.
- [ ] deploy a basic deployment of companion
- [ ] reconcile the deployment
- [ ] add owned resources
- [ ] add watchers
- [ ] add predicates to filter out unnessasry reconciliations.
- [ ] Unit tests.
- [ ] scaffold integration tests using envtests.

**Comment by mfaizanse** [comment]
1. Fetch the secrets for HANA Vector DB, Redis, and AI-Core.
2. Combine the configs in a secret which would be mounted to kyma-companion-backend.
3. Create the secret on k8s.
4. Create a deployment of kyma-companion-backend.

**Comment by mfaizanse** [comment]
Sample secrets and configMap:
```
apiVersion: v1
data:
 test-key: "test-value"
kind: ConfigMap
metadata:
 name: companion-ai-core
 namespace: kyma-system
---
apiVersion: v1
data:
 test-key: dGVzdC12YWx1ZQ==
kind: Secret
metadata:
 name: companion-ai-core
 namespace: kyma-system
type: Opaque
---
apiVersion: v1
data:
 test-key: dGVzdC12YWx1ZQ==
kind: Secret
metadata:
 name: companion-hana-db
 namespace: kyma-system
type: Opaque
---
apiVersion: v1
data:
 test-key: dGVzdC12YWx1ZQ==
kind: Secret
metadata:
 name: companion-redis
 namespace: kyma-system
type: Opaque
```
