### ISSUE TITLE
Design the Companion Manager CR

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#59]
**Description:**
To define and implement Custom Resource Definitions (CRDs) and a Companion Custom Resource (CR) to efficiently manage configurations and secrets for HANA Vector SB, Redis, and AI-Core. Additionally, ensure that all updates are comprehensively documented.

The manager was implemented in this issue #58 
Cluster creation information is described in[ this issue](https://github.tools.sap/kyma/ai-force/blob/main/docs/infrastructure/setup.md)
 
**Tasks:**
1. Discuss within the team how CRDs should look like
2. **Facilitate Companion Custom Resource:** Implement the Companion CR to handle configurations and secrets for HANA Vector SB, Redis, and AI-Core. - Provide the necessary configuration from existing HandDB, Redis, AI-Core to the backend- Provide Flexibility in CRDs for potential automation
3. **Documentation:** Update the documentation to include CR information into the companion manager
**Acceptance Criteria:**

- [x] **Team Agreement:** CRD structure documented and agreed upon by the team.
- [x] **Functionality:** Companion CR handles configurations and secrets for HANA Vector SB, Redis, and AI-Core.
- [x] **Flexibility:** CRDs support potential automation.
- [x] **Comprehensive Documentation:** CRDs are documented and documentation integrated into the companion manager documentation

**Comment by Teneroy** [comment]
For later: reconciliation and validation

**Comment by the1bit** [comment]
Related files and documents: https://github.com/the1bit/kyma-companion-manager/tree/59-Design-the-Companion-Manager-CR

**Comment by the1bit** [comment]
Documentation with options: https://github.com/the1bit/kyma-companion-manager/blob/59-Design-the-Companion-Manager-CR/CRD.md

**Comment by mfaizanse** [comment]
A suggestion for CR:

```
apiVersion: operator.kyma-project.io/v1alpha1
kind: Companion
metadata:
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/component: kyma-companion-manager
    app.kubernetes.io/part-of: kyma-companion-manager
  name: default
  namespace: kyma-system
spec:
  hanadbSecret: name/namespace
  redisSecret: name/namespace
  aiCoreSecret: name/namespace
  aiCoreConfigMap: name/namespace
  companionConfig:
    replicas: 
      min: 2
      max: 3
    resources:
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi
```

**Comment by marcobebway** [comment]
CR suggestion:

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Companion
metadata:
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/component: kyma-companion-manager
    app.kubernetes.io/part-of: kyma-companion-manager
  name: default
  namespace: kyma-system
spec:
  aiCore:
    secret:
      name: any
      namespace: any
    configMap:
      name: any
      namespace: any
  hanaDB:
    secret:
      name: any
      namespace: any
  redis:
    secret:
      name: any
      namespace: any
  companion:
    replicas:
      min: 2
      max: 3
    resources:
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi
```

**Comment by the1bit** [comment]
I have additional 2 suggestions according to your feedback.

**Required secrets:**

- ai-core: it has a dedicated secret
- companion: it would contain the current configMap related required values
- hana: Hana related secret
- redis: Redis related secret


## 1. Only secrets for all related namespaces



```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Companion
metadata:
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/component: kyma-companion-manager
    app.kubernetes.io/part-of: kyma-companion-manager
  name: default
  namespace: kyma-system
spec:
  aicoreSecret: ai-core/aicore
  companionSecret: companion/aicore
  hanaCloudSecret: companion/hana-cloud
  redisSecret: companion/redis
  companion:
    replicas:
      min: 1
      max: 3
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi
```

## 2. Dedicated section for all 

In this scenario we can expand any component related configuration section easily.


```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Companion
metadata:
  labels:
    app.kubernetes.io/name: default
    app.kubernetes.io/component: kyma-companion-manager
    app.kubernetes.io/part-of: kyma-companion-manager
  name: default
  namespace: kyma-system
spec:
  aicore:
    secret: ai-core/aicore
  hanaCloud:
    secret: companion/hana-cloud
  redis:
    secret: companion/redis
  companion:
    secret: companion/aicore
    replicas:
      min: 1
      max: 3
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 256Mi
```

**Comment by the1bit** [comment]
Final PRs:

- Code modification: https://github.com/kyma-project/kyma-companion-manager/pull/14
- Documentation: https://github.tools.sap/kyma/ai-force/pull/202
