### ISSUE TITLE
Create Gardener Cluster and Deploy Kyma with GitHub Action for Single-Namespace Problem Deployment

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#91]
### Description:
Create a Gardener cluster and deploy Kyma on it. Write a GitHub Action that will deploy Kyma cluster, iterate over a folder containing single-namespace problems and deploy them to the Gardener cluster. This GitHub Action should be designed to be triggered on-demand.

### Subtasks:

**1. Create Gardener Cluster:**

- Set up a new Gardener cluster.
- Ensure proper configuration and access permissions.
- Document the process of creation and configuration of the cluster

**2. Write GitHub Action to:**

- Authenticate and connect to the Gardener cluster.
- Clean up previously deployed things on the cluster.
- Deploy Kyma cluster
- Iterate over the folder containing single-namespace problems.
- Deploy each problem to the Kyma cluster.
- Include error handling and logging for troubleshooting.

**3. Trigger on-Demand:**

- Configure the GitHub Action to be triggered manually.

**4. Testing and Verification:**

- Test the GitHub Action to ensure it correctly deploys the problems to the Gardener cluster.

### Acceptance Criteria:

- [ ] The Gardener cluster is created successfully.
- [ ] The documentation for the process of creation and configuration of the cluster is written
- [x]  Proper configuration and access permissions are verified.
- [x]  The GitHub Action authenticates and connects to the Gardener cluster.
- [x]  The GitHub Action successfully cleans up previously deployed resources on the cluster.
- [x]  Kyma is deployed successfully on the Gardener cluster.
- [x]  The GitHub Action iterates over the folder and deploys all single-namespace problems to the Kyma cluster.
- [x]  The GitHub Action can only be triggered manually.

**Comment by Teneroy** [comment]
Add the task for one person working on the initial design. Then we do a team meeting to agree on the design (before the sprint preferably)

**Comment by marcobebway** [comment]
Tasks:

- Provision a gardener cluster. @marcobebway 
- Create a GH action to connect to the gardener cluster. @grischperl

**Comment by grischperl** [comment]
### Manually provision Gardener cluster
- [x] The Gardener cluster is created successfully.
   - 3 clusters with slightly different setup created: `comp-tests-0`, `comp-tests-1`, `comp-tests-2`
- [ ] The documentation for the process of creation and configuration of the cluster is written
   - documentation TBD
- [x]  Proper configuration and access permissions are verified.

### GitHub Action connects
- [x]  The GitHub Action authenticates and connects to the Gardener cluster.
- [x]  The GitHub Action can only be triggered manually.
**PR** #106 

### GitHub Action initializes
- [ ]  The GitHub Action successfully cleans up previously deployed resources on the cluster.
- [ ]  Kyma is deployed successfully on the Gardener cluster.
**PR** #118 

### GitHub Action deploys
- [ ]  The GitHub Action iterates over the folder and deploys all single-namespace problems to the Kyma cluster.
**PR** TBA
