### ISSUE TITLE
Extend Dataset for Testing Framework

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#92]
### Description
We need to extend the dataset used in our testing framework to include new scenarios, expectations, and YAML files for the deployment of problems for those scenarios on the cluster. The new dataset will enhance our ability to evaluate and validate AI models effectively. For the scope of this task, it is sufficient to include all the examples prepared for D-COM.

### Tasks

**1. Identify New Scenarios:**

- Use the examples prepared for D-COM as the source for new scenarios.
- Review and finalize the list of scenarios with the team.

**2. Define Expectations for Each Scenario:**

- Ensure that scenarios adhere agreed data structure
- Draft detailed expectations for each new scenario based on D-COM examples.
- Include expectation IDs, statements, weights, and categories.
- Review and finalize expectations with the team.

**3. Develop Deployment YAMLs and shells for deployment:**

- Create YAML files and shell scripts for each scenario to enable deployment on the cluster.
- Ensure YAMLs and shell scripts tested for correctness.

**4. Integrate New Data into the Framework:**

- Add the new scenarios, expectations, and YAMLs to the framework.
- Ensure compatibility with existing functionalities.
- Test the integration to verify that the framework processes the new data correctly.

### Acceptance Criteria

- [ ] A diverse set of new scenarios and corresponding expectations from the D-COM examples have been added to the dataset.
- [ ] YAML files  and shell scripts for deploying problems on the cluster are created and tested.
- [ ] The new dataset is integrated into the framework and passes all integration tests.

**Comment by friedrichwilken** [comment]
I started working on this and opened a PR, which is not finished. I started to add some docs that can help with the creation of new scenarios. We need to review the existing D-Com scenarios and find out, wich ones are worth adding to our tests. We also need to talk about my work as soon as possible so I do not move into the wrong direction, especially when it comes to expectations.

**Comment by friedrichwilken** [comment]
Here is a follow-up issue: https://github.com/kyma-project/kyma-companion/issues/141
